name: Run Security Scan

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and Push on DockerHub"]
    types:
      - completed

permissions:
  contents: read

jobs:
  security-scan:
    permissions:
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Scan Ubuntu Noble Image
        uses: docker/scout-action@v1
        with:
          command: cves
          image: docker.io/karfee111/do-agent:noble-latest
          sarif: 'scout-noble-results.sarif'
          only-severities: 'high,critical'

      - name: Scan Debian Trixie Image
        uses: docker/scout-action@v1
        with:
          command: cves
          image: docker.io/karfee111/do-agent:trixie-latest
          sarif: 'scout-trixie-results.sarif'
          only-severities: 'high,critical'

      - name: Upload Noble results to GitHub
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'scout-noble-results.sarif'
          category: 'noble-image'

      - name: Upload Trixie results to GitHub
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'scout-trixie-results.sarif'
          category: 'trixie-image'
