name: Run Trivy Scan

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and Push on DockerHub"]
    types:
      - completed

permissions:
  contents: read

jobs:
  trivy-scan:
    permissions:
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Trivy CLI
        run: |
          sudo apt-get update && sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb-release -sc) main" | sudo tee /etc/apt/sources.list.di/trivy.list
          sudo apt-get update && sudo apt-get install -y trivy

      - name: Scan Ubuntu Noble Image
        run: |
          trivy image \
            --format sarif \
            --severity HIGH,CRITICAL \
            --output trivy-noble-results.sarif \
            docker.io/karfee111/do-agent:noble-latest

      - name: Scan Debian Trixie Image
        run: |
          trivy image \
            --format sarif \
            --severity HIGH,CRITICAL \
            --output trivy-trixie-results.sarif \
            docker.io/karfee111/do-agent:trixie-latest

      - name: Upload Trivy Noble results
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: trivy-noble-results.sarif
          category: noble-image

      - name: Upload Trivy Trixie results
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: trivy-trixie-results.sarif
          category: trixie-image
